### ISSUE TITLE
특정 문자들이 사라지는 현상

### ISSUE THREAD

**Issue by jeongukjae** [hyunwoongko/kss#16]
```python
>>> import kss
>>> print(kss.split_sentences("Shift + [."))
['Shift + .']
>>> print(kss.split_sentences("Shift + (."))
['Shift + .']
>>> print(kss.split_sentences("Shift + {."))
['Shift + .']
```

엣지 케이스로 보이는 현상을 발견하여 이슈를 남겨놓습니다.
위처럼 특정 커맨드를 설명하는 문장을 넣을 때 괄호들이 사라집니다.

```sh
$ pip freeze | grep kss
kss==2.5.1
$ python -V
Python 3.8.7
```

**Comment by hyunwoongko** [comment]
안녕하세요. 이 문제는 구현에 있는 문제 때문인데요.
이미 인지하고 있는 문제입니다. 
차후에 수정하는 것을 고민해보겠습니다.

감사합니다!

**Comment by DataLama** [comment]
@hyunwoongko 

아래 문제가 해당 이슈와 관련 있는것 같아서, 케이스 추가합니다.

```python
>>> import kss
>>> print(kss.split_chunks("안녕하세요 :-)저는 사계절내내 건조한 피부를 갖고 있는데요"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/kss/kss.py", line 402, in split_chunks
    indexes = split_sentences_index(text)
  File "/usr/local/lib/python3.8/dist-packages/kss/kss.py", line 384, in split_sentences_index
    SentenceIndex(offset + text.index(sentence),
ValueError: substring not found
```

```
$ pip freeze | grep kss
kss==2.5.1
$ python3 -V
Python 3.8.5
```

**Comment by hyunwoongko** [comment]
2.6.0으로 업데이트 하면서 문제를 해결했습니다. 확인해보시겠어요?
`pip install kss --upgrade`로 업데이트 해주세요.

**Comment by hyunwoongko** [comment]
이슈를 닫겠습니다. 관련 문제가 다시 발생하면 말씀해주세요~
