### ISSUE TITLE
M1 맥북에서 실행 실패

### ISSUE THREAD

**Issue by ashen1dev** [hyunwoongko/kss#25]
>>> from kss import split_sentences
>>> text = "강남역 맛집으로 소문난 강남 토끼정에 다녀왔습니다 회사 동료 분들과 다녀왔는데 분위기도 좋고 음식도 맛있었어요 다만, 강남 토끼정이 강남 쉑쉑버거 골목길로 쭉 올라가야 하는데 다들 쉑쉑버거의 유혹에 넘어갈 뻔 했답니다"
>>> split_sentences(text)
[Korean Sentence Splitter]: Initializing Pynori...
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/phy/opt/anaconda3/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/phy/opt/anaconda3/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/Users/phy/opt/anaconda3/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/Users/phy/opt/anaconda3/lib/python3.8/site-packages/kss/kss.py", line 266, in _split_sentences
    eojeols = _morph.pos(text=text, backend=backend)
  File "/Users/phy/opt/anaconda3/lib/python3.8/site-packages/kss/morph.py", line 46, in pos
    _pos = self.pynori.do_analysis(
AttributeError: 'NoneType' object has no attribute 'do_analysis'
"""

예제 코드가 실행이 안 되네요. M1문제인지... 설치는 pip로 했습니다. conda를 써서 그런걸까요?

**Comment by goreng2** [comment]
@hyunwoongko 
안녕하세요. 좋은 라이브러리 관리에 감사드립니다.

```python
from kss import split_sentences

if __name__ == '__main__':
    text1 = "오늘 여러분과 함께 리뷰해 볼 영화는 바로 디즈니 픽사의 영화 '업'입니다 저는 이 영화를 고등학교 영어시간에 처음 보게되었는데요, 수능날을 맞이해서 고등학교 추억이 담긴 영화를 오늘 여러분께 소개해드리려고 해요~ㅎㅎㅎ 한방울 눈물과 한바탕 웃음 마음 속에 담고 싶은 단 하나의 걸작 평생 모험을 꿈꿔 왔던 ‘칼’ 할아버지는 수천 개의 풍선을 매달아 집을 통째로 남아메리카로 날려 버리는데, ‘칼’ 할아버지의 이 위대한 모험에 초대 받지 않은 불청객이 있었으니, 바로 황야의 탐험가 ‘러셀’ 지구상에 둘도 없을 이 어색한 커플이 함께 하는 대모험 그들은 과연 남미의 잃어버린 세계에서 사라져 버린 꿈과 희망, 행복을 다시 찾을 수 있을까? 여러분은 디즈니 영화를 좋아하시 나요? 저는 디즈니보다는 픽사를 훨씬 더 좋아하는 편인데요 디즈니와 픽사가 합병한 뒤, 저는 디즈니 픽사 영화가 인생영화 중 대부분을 차지할 정도로 정말 즐겨보고 있어요"
    text2 = "동영상 촬영이 금지되어있어 노홍철 씨의 열정 넘치는 강연을 그대로 보여 드리지 못하는 점 너무 아쉽네요 ㅠㅠ 간단한 행사스케치로나마 참고해주세요~ 노홍철의 열정 Talk 행사는 개그맨 김범용 씨가 맡아주셨고 오프닝 무대는 위대한 탄생3 탑3로 이름을 날린 오병길 씨의 노래로 뜨겁게 달궈졌습니다^^ 이날 초대된 로열블루와 블루 멤버십 고객분들의 환호로 삼성홍보관 딜라이트 안이 가득 차더군요! (오병길 씨의 노래 잘하는 비법은 무엇일까요? 꾸준한 모창연습이라고… ㅋ) 곧이어 이 날 행사의 메인이었던 노홍철씨의 열정 Talk가 본격적으로 시작되었습니다"
    print(split_sentences([text1, text2]))
```
위와 같은 예제를 실행했을 때, 아래와 같은 에러가 발생합니다.
`str`은 이상없이 동작하는데, `List[str]` 형태는 안되네요
```
Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\pp\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\Anaconda3\envs\pp\lib\concurrent\futures\process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "C:\Users\Anaconda3\envs\pp\lib\concurrent\futures\process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "C:\Users\Anaconda3\envs\pp\lib\site-packages\kss\kss.py", line 263, in _split_sentences
    eojeols = _morph.pos(text=text, backend=backend)
  File "C:\Users\Anaconda3\envs\pp\lib\site-packages\kss\morph.py", line 46, in pos
    _pos = self.pynori.do_analysis(
AttributeError: 'NoneType' object has no attribute 'do_analysis'
```

**Comment by hyunwoongko** [comment]
확인 후 답변 드리겠습니다. 감사합니다.
