### ISSUE TITLE
특정 문장에 대한 에러 이슈

### ISSUE THREAD

**Issue by yjy2026** [hyunwoongko/kss#28]
안녕하세요. 
우선, 멋진 작업 감사드립니다. 잘 쓰고 있습니다 ㅎㅎ

특정 문자열에 대해 아래와 같은 에러가 발생하여 보고드립니다.

```
>>> kss.split_sentences("1'1″")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/kss/kss.py", line 185, in split_sentences
    return results[0]
IndexError: list index out of range
```

1. backend 에 무관한 듯 보입니다.
2. ' 와 ″ 문자와 관계가 있는 것 같습니다.
3. 위와 관련된 에러가 나는 문자열을 포함하는 문자열은 모두 에러가 발생합니다.

여러모로 테스트해봤는데, 에러가 발생하는 조건을 찾기가 쉽지 않더군요.

1. 우선, 두 문자를 단독으로 사용하는 경우는 문제가 없습니다.
```
>>> kss.split_sentences("'″")
["'″"]
>>> kss.split_sentences("″'")
["″'"]
>>> kss.split_sentences("''")
["''"]
>>> kss.split_sentences("″″")
['″″']
```
2. 기본적으로 `[0-9a-zA-Z]'[0-9a-zA-Z]″` 세팅에서 에러가 발생하는 것으로 보입니다.
```
>>> kss.split_sentences("1'1″")
(에러)
>>> kss.split_sentences("s's″")
(에러)
>>> kss.split_sentences("1's″")
(에러)
>>> kss.split_sentences("s'1″")
["s'1″"] (이 경우는 예외의 예외(?)로 에러가 나지 않습니다.)
```
3. 알파벳과 숫자의 경우에만 에러가 발생하는 듯 하며, 한글에서는 발생하지 않는 것 같습니다.
```
>>> kss.split_sentences("가'a″")
["가'a″"]
>>> kss.split_sentences("가'가″")
["가'가″"]
>>> kss.split_sentences("a'가″")
["a'가″"]
>>> kss.split_sentences("1'가″")
["1'가″"]
>>> kss.split_sentences("가'1″")
["가'1″"]
```
4. `[0-9a-zA-Z]'(이 사이에 문자 추가)[0-9a-zA-Z]″`

추가한 문자열의 길이가 1 인 case
```
>>> kss.split_sentences("1'b2″")
["1'b2″"]
>>> kss.split_sentences("1'bb″")
["1'bb″"]
>>> kss.split_sentences("1'2b″")
["1'2b″"]
>>> kss.split_sentences("1'22″")
(에러)
>>> kss.split_sentences("c'22″")
["c'22″"]
>>> kss.split_sentences("c'2e″")
["c'2e″"]
>>> kss.split_sentences("c'ee″")
["c'ee″"]
>>> kss.split_sentences("c'e2″")
(에러)
```
사이에 추가되는 문자열의 길이가 2 이상일 경우에서는 에러가 발생하지 않는 듯 합니다.
```
>>> kss.split_sentences("8'111″")
["8'111″"]
>>> kss.split_sentences("8's11″")
["8's11″"]
>>> kss.split_sentences("8'1s1″")
["8'1s1″"]
>>> kss.split_sentences("8'11s″")
["8'11s″"]
>>> kss.split_sentences("8'1ss″")
["8'1ss″"]
>>> kss.split_sentences("8's1s″")
["8's1s″"]
>>> kss.split_sentences("8'ss1″")
["8'ss1″"]
>>> kss.split_sentences("8'sss″")
["8'sss″"]
>>> kss.split_sentences("c'111″")
["c'111″"]
>>> kss.split_sentences("c'11s″")
["c'11s″"]
>>> kss.split_sentences("c'1s1″")
["c'1s1″"]
>>> kss.split_sentences("c's11″")
["c's11″"]
>>> kss.split_sentences("c'ss1″")
["c'ss1″"]
>>> kss.split_sentences("c's1s″")
["c's1s″"]
>>> kss.split_sentences("c'1ss″")
["c'1ss″"]
>>> kss.split_sentences("c'sss″")
["c'sss″"]
```

확인 부탁드리겠습니다.

감사합니다.

----
추가 : `[0-9a-zA-Z]'[0-9a-zA-Z]″` 뿐만 아니라, `[0-9a-zA-Z]'[0-9a-zA-Z]"` (″ 가 아닌 " 가 붙는 경우) 에도 에러가 발생하네요.

**Comment by hyunwoongko** [comment]
제가 시간이 나면 확인해보도록 하겠습니다. 감사합니다.

**Comment by hyunwoongko** [comment]
3.4 버전에서 해결했습니다. 늦은 대응 죄송합니다.
