### ISSUE TITLE
\u200b (no width whitespace) 있는 문장에 대한 에러

### ISSUE THREAD

**Issue by hannabros** [hyunwoongko/kss#29]
안녕하세요:)

특정 문자열이 포함된 문장에 대해 문장 분리가 되지 않는 이슈가 있어 보고합니다.
```
>>> kss.split_sentences('분리 할 수 ​​있다.')
[Korean Sentence Splitter]: Initializing Pynori...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/ir/lib/python3.7/site-packages/kss/kss.py", line 185, in split_sentences
    return results[0]
IndexError: list index out of range
```

위 예시 문장에 들어가 있는 '분리 할 수 ​​있다.' 에 \u200b가 포함되어 있어 문장 분리가 되지 않았습니다.

**Comment by hyunwoongko** [comment]
리포트 감사드립니다. 시간나면 확인후 수정하도록 하겠습니다.

**Comment by hyunwoongko** [comment]
3.4버전에서 해결했습니다.
