### ISSUE TITLE
특정 문장에서 오류를 뱉는 문제

### ISSUE THREAD

**Issue by newdboy** [hyunwoongko/kss#35]
버그인 듯 보입니다.
오류를 나타내는 문장은 다음과 같습니다.
` '그것이 잘 적혀 있는지 확인해야 한다고 했기 때문이다. EBS 미래교육연구소 최홍규 박사도 그렇게 말했다'`

아래 문장의 경우 정상적으로 작동합니다.
1) 문장 사이의 whitespace를 삭제하는 경우
` '그것이 잘 적혀 있는지 확인해야 한다고 했기 때문이다.EBS 미래교육연구소 최홍규 박사도 그렇게 말했다'`
2) 문장 사이의 구두점을 삭제하는 경우
` '그것이 잘 적혀 있는지 확인해야 한다고 했기 때문이다 EBS 미래교육연구소 최홍규 박사도 그렇게 말했다'`

아래는 오류 메세지 입니다.
```
>>> from kss import split_sentences
>>> tst = '그것이 잘 적혀 있는지 확인해야 한다고 했기 때문이다. EBS 미래교육연구소 최홍규 박사도 그렇게 말했다'
>>> split_sentences(text=tst, backend='mecab', use_heuristic=True)
Traceback (most recent call last):
  File "/Users/kintch/.conda/envs/newer/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/kintch/.conda/envs/newer/lib/python3.7/site-packages/kss/kss.py", line 185, in split_sentences
    return results[0]
IndexError: list index out of range
```

**Comment by newdboy** [comment]
뭐가 바뀌었는지 모르겠지만, 다시 깔아보니 잘되네요...

**Comment by hyunwoongko** [comment]
```python
tst = '그것이 잘 적혀 있는지 확인해야 한다고 했기 때문이다. EBS 미래교육연구소 최홍규 박사도 그렇게 말했다'
output = kss.split_sentences(text=tst, backend='mecab', use_heuristic=True)
print(output)
```
```
['그것이 잘 적혀 있는지 확인해야 한다고 했기 때문이다.', 'EBS 미래교육연구소 최홍규 박사도 그렇게 말했다']
```

저도 해보니까 잘 되네요. 뭐가 문제인지는 모르겠지만.. 클로징하겠습니다.
