### ISSUE TITLE
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by newdboy** [hyunwoongko/kss#36]
python3.8에서만 유독 저 에러메세지를 뱉네요..
물론 num_workers=1로 하면 잘 작동하구요.
왜 그럴까요..

```
>>> tst = '그것이 잘 적혀 있는지 확인야 한다고 했기 때문이다.EBS 미래교육연구소 최홍규 박사도 그렇게 말했다.'
>>> split_sentences(text=tst, backend='mecab', use_heuristic=True, num_workers=-1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/runpy.py", line 264, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/runpy.py", line 234, in _get_code_from_file
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kintch/PycharmProjects/pclur_beta0.1/<input>'
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/runpy.py", line 264, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/runpy.py", line 234, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kintch/PycharmProjects/pclur_beta0.1/<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/runpy.py", line 264, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/runpy.py", line 234, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kintch/PycharmProjects/pclur_beta0.1/<input>'
Traceback (most recent call last):
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/site-packages/kss/kss.py", line 126, in split_sentences
    for input_text in preprocessed_list:
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/Users/kintch/.conda/envs/pclur_beta0.1/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

```

**Comment by jungin-42maru** [comment]
저도 같은 에러 나옵니다. 해결하셨나요?

**Comment by hyunwoongko** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kintch/PycharmProjects/pclur_beta0.1/<input>'
```

이게 문제인 것 같은데, 음.. 환경 문제로 보입니다. kss 쪽 문제는 아닌 것 같네요.

**Comment by hyunwoongko** [comment]
<img width="895" alt="스크린샷 2022-02-16 오전 6 30 09" src="https://user-images.githubusercontent.com/38183241/154152512-6f9c2d4d-3b55-4734-a39f-16260cc76369.png">

혹시 몰라서 파이썬 3.8에서 테스트 해봤구요. 일단 파이썬 3.8과의 호환성 문제는 아닌 것 같습니다.
파이참 프로젝트에서 프로젝트 환경설정을 다시 해보시겠어요?
