### ISSUE TITLE
3.7.0) AttributeError: module 'emoji' has no attribute 'UNICODE_EMOJI'

### ISSUE THREAD

**Issue by Clarit7** [hyunwoongko/kss#52]
```
❯ pip install kss
Collecting kss
  Using cached kss-3.7.0.tar.gz (42.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/my/6tpt42kd6cjclj6klhkjsf9h0000gn/T/pip-install-0gw7w00y/kss_dde11240c93144d69851b4d47e762b8b/setup.py", line 38, in <module>
          exec(version_file.read(), version)
        File "<string>", line 10, in <module>
        File "/private/var/folders/my/6tpt42kd6cjclj6klhkjsf9h0000gn/T/pip-install-0gw7w00y/kss_dde11240c93144d69851b4d47e762b8b/kss/__init__.py", line 10, in <module>
          from kss.kss import split_chunks, split_sentences
        File "/private/var/folders/my/6tpt42kd6cjclj6klhkjsf9h0000gn/T/pip-install-0gw7w00y/kss_dde11240c93144d69851b4d47e762b8b/kss/kss.py", line 23, in <module>
          from kss.base import (
        File "/private/var/folders/my/6tpt42kd6cjclj6klhkjsf9h0000gn/T/pip-install-0gw7w00y/kss_dde11240c93144d69851b4d47e762b8b/kss/base.py", line 17, in <module>
          from kss.morph import MorphExtractor
        File "/private/var/folders/my/6tpt42kd6cjclj6klhkjsf9h0000gn/T/pip-install-0gw7w00y/kss_dde11240c93144d69851b4d47e762b8b/kss/morph.py", line 15, in <module>
          from kss.pynori.korean_analyzer import KoreanAnalyzer
        File "/private/var/folders/my/6tpt42kd6cjclj6klhkjsf9h0000gn/T/pip-install-0gw7w00y/kss_dde11240c93144d69851b4d47e762b8b/kss/pynori/korean_analyzer.py", line 2, in <module>
          from kss.pynori.korean_tokenizer import KoreanTokenizer
        File "/private/var/folders/my/6tpt42kd6cjclj6klhkjsf9h0000gn/T/pip-install-0gw7w00y/kss_dde11240c93144d69851b4d47e762b8b/kss/pynori/korean_tokenizer.py", line 26, in <module>
          from kss.pynori.dict.user_dictionary import UserDictionary
        File "/private/var/folders/my/6tpt42kd6cjclj6klhkjsf9h0000gn/T/pip-install-0gw7w00y/kss_dde11240c93144d69851b4d47e762b8b/kss/pynori/dict/user_dictionary.py", line 2, in <module>
          from kss.pynori.dict.character_definition import CharacterDefinition
        File "/private/var/folders/my/6tpt42kd6cjclj6klhkjsf9h0000gn/T/pip-install-0gw7w00y/kss_dde11240c93144d69851b4d47e762b8b/kss/pynori/dict/character_definition.py", line 13, in <module>
          _emojis.update(emoji.UNICODE_EMOJI[lang])
      AttributeError: module 'emoji' has no attribute 'UNICODE_EMOJI'
      [end of output]
```

안녕하세요. 설치 시 위와 같은 에러가 발생하였습니다.
두시간 전에 업데이트 하셨길래 3.6.4로 낮춰서 설치하니 정상 설치 되었습니다.
m1맥 입니다.
감사합니다.

**Comment by hyunwoongko** [comment]
https://github.com/hyunwoongko/kss/issues/44 와 중복으로 보이구요.
에러 발생시에 `emoji` 라이브러리 버전 확인 가능하실까요?

**Comment by hyunwoongko** [comment]
https://github.com/hyunwoongko/kss/blob/main/setup.py#L10
여기에 버전이 명시되어있기 때문에 설치시에 1.2.0으로 설치가 되긴 할텐데
이후에 추가로 다른 라이브러리들 설치하시면서 변경되지 않으셨는지 확인 부탁드립니다.

**Comment by Clarit7** [comment]
3.6.4 설치시에 emoji 1.2.0으로 잘 설치된 것 같습니다. 그 전에 3.7.0 설치시엔 이유는 모르겠지만 의존 패키지가 자동으로 설치가 안되어서 emoji 2.2.0을 수동으로 설치했었는데 그게 문제였나 봅니다. 늦은시간 답변 감사합니다 :)

**Comment by hyunwoongko** [comment]
아마도 제가 배포를 평소랑 다른환경에서 해서 그런지 디펜던시 쪽에 이슈가 있는 것 같습니다.
가능한 빠른 시일내에 수정하도록 하겠습니다. 감사합니다.
이슈는 해당 문제가 해결되면 클로징 하도록 하겠습니다.

**Comment by hyunwoongko** [comment]
v3.7.1에서 해결되었습니다.
