### ISSUE TITLE
Fix bug on split_chunks

### ISSUE THREAD

**Issue by hyunwoongko** [hyunwoongko/kss#53]
```python
import kss

kss.split_chunks("", max_length=10)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\MY\Github\kss\kss\kss.py", line 261, in split_chunks
    for _txt in _text
  File "C:\Users\MY\Github\kss\kss\kss.py", line 261, in <listcomp>
    for _txt in _text
  File "C:\Users\MY\Github\kss\kss\kss.py", line 664, in _split_chunks
    chunk = get_chunk_with_index(text, span)
  File "C:\Users\MY\Github\kss\kss\base.py", line 447, in get_chunk_with_index
    start = span[0][0]
IndexError: list index out of range
```

**Comment by hyunwoongko** [comment]
v3.7.2에서 해결됨.
