### ISSUE TITLE
KeyError: 'EMOJI'

### ISSUE THREAD

**Issue by singleheart** [hyunwoongko/kss#56]
## 개요
#51 이슈가 kss 3.7.3 버전에서도 이모지를 포함한 문서들에서 발생하는 것을 확인하고 리포트합니다. 모든 이모지에 대해서 에러가 발생하지는 않는 것 같고 첨부한 문서 (b.txt)와 같은 특정 조건에서 발생하는 것 같습니다. 

## 재현 방법

1. 첨부한 b.txt를 다운로드
2. 아래 코드를 실행
```python
import kss
with open("b.txt") as f:
    for line in f.readlines():
        print(kss.split_sentences(line))
```
3. 아래와 같은 에러 발생
```
[Korean Sentence Splitter]: You can install `python-mecab-kor` for faster kss execution.
Try to install it using `pip install python-mecab-kor`.
Refer https://github.com/hyuwoongko/python-mecab-kor for more details.

[Korean Sentence Splitter]: Initializing Pynori...
[]
['}']
[]
[]
[]
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    print(kss.split_sentences(line))
  File "/home/singleheart/.pyenv/versions/ksstest/lib/python3.8/site-packages/kss/kss.py", line 183, in split_sentences
    results += [
  File "/home/singleheart/.pyenv/versions/ksstest/lib/python3.8/site-packages/kss/kss.py", line 184, in <listcomp>
    _split_sentences(
  File "/home/singleheart/.pyenv/versions/ksstest/lib/python3.8/site-packages/kss/kss.py", line 302, in _split_sentences
    eojeols = _morph.pos(text=text, backend=backend)
  File "/home/singleheart/.pyenv/versions/ksstest/lib/python3.8/site-packages/kss/morph.py", line 65, in pos
    _pos = self.pynori.do_analysis(
  File "/home/singleheart/.pyenv/versions/ksstest/lib/python3.8/site-packages/kss/pynori/korean_analyzer.py", line 63, in do_analysis
    while self.kor_tokenizer.increment_token():
  File "/home/singleheart/.pyenv/versions/ksstest/lib/python3.8/site-packages/kss/pynori/korean_tokenizer.py", line 356, in increment_token
    self.parse()
  File "/home/singleheart/.pyenv/versions/ksstest/lib/python3.8/site-packages/kss/pynori/korean_tokenizer.py", line 472, in parse
    if self.character_definition.isGroup(firstCharacter) is False:
  File "/home/singleheart/.pyenv/versions/ksstest/lib/python3.8/site-packages/kss/pynori/dict/character_definition.py", line 44809, in isGroup
    return groupMap[character_category_map(ch)]
KeyError: 'EMOJI'
```

### 테스트 데이터
[b.txt](https://github.com/hyunwoongko/kss/files/10139847/b.txt)

## 버전 정보
```
$ pip show kss  
Name: kss
Version: 3.7.3
Summary: A Toolkit for Korean sentence segmentation
Home-page: https://github.com/hyunwoongko/kss
Author: Hyunwoong Ko
Author-email: kevin.ko@tunib.ai
License: BSD 3-Clause "New" or "Revised" License
Location: /home/singleheart/.pyenv/versions/3.8.12/envs/ksstest/lib/python3.8/site-packages
Requires: emoji, more-itertools, regex
Required-by: 
```

**Comment by singleheart** [comment]
테스트 환경에 sudo 권한이 없어서 `python-mecab-kor`는 설치하지 못했습니다

**Comment by singleheart** [comment]
잘 되는 것을 확인했습니다. 감사합니다!
